Rendering of struts as lines is working.
The instanced renderer is still giving me compilation problems:

Error compiling shader: ERROR: 0:22: Incompatible types in initialization (and no available implicit conversion)

Do demonstrate strut rendering, I have disabled creation of the instanced
renderer, and it is never used because "loading" remains true.